name: auto-pr-approval
on:
  pull_request:
    branches:
      - main

jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - id: approve
        uses: actions/github-script@v7
        with:
          result-encoding: string
          retries: 3
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: github.event.number,
              event: "COMMENT",
              body: "hello"
            })
