name: auto-pr-approval
on:
  pull_request:
    branches:
      - main

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: contains(fromJSON('["dependabot[bot]", "renovate[bot]"]'), github.actor)
    steps:
      - id: approve
        uses: actions/github-script@v7
        with:
          result-encoding: string
          retries: 3
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.number }},
              event: "APPROVE",
              body: "auto approved"
            })
